mixed-port: 7890
allow-lan: true
bind-address: "*"
mode: rule
log-level: info
external-controller: 0.0.0.0:9090
external-ui: /root/.config/mihomo/ui
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"
secret: "changeme"

dns:
  enable: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query

listeners:
  - name: hk
    type: mixed
    port: 1081
    proxy: HK

  - name: jp
    type: mixed
    port: 1082
    proxy: JP

  - name: us
    type: mixed
    port: 1083
    proxy: US

  - name: sg
    type: mixed
    port: 1084
    proxy: SG

  - name: us-east
    type: mixed
    port: 1085
    proxy: US-EAST

proxy-providers:
  my-sub:
    type: file
    path: /root/.config/mihomo/proxy.yaml
    health-check:
      enable: true
      interval: 600
      url: https://www.gstatic.com/generate_204

proxy-groups:
  - name: HK
    type: select
    use:
      - my-sub
    filter: "香港"

  - name: JP
    type: select
    use:
      - my-sub
    filter: "东京"

  - name: US
    type: select
    use:
      - my-sub
    filter: "硅谷"

  - name: SG
    type: select
    use:
      - my-sub
    filter: "新加坡"

  - name: US-EAST
    type: select
    use:
      - my-sub
    filter: "弗吉尼亚"

rules:
  - MATCH,DIRECT
